# Generated by Django 3.2.5 on 2021-07-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_publication_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
