# Generated by Django 3.2.5 on 2021-07-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_role_signup_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
