# Generated by Django 3.2.5 on 2021-07-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowing_price_per_day',
        ),
    ]
